const INITIAL_EMPLOYEES = [
  {
    id: "ZAK-1001",
    fullName: "Aarav Sharma",
    email: "aarav.sharma@zakvid.in",
    phone: "+91 98765 43210",
    location: "Bengaluru",
    department: "Engineering",
    designation: "Lead Frontend Architect",
    salary: 1850000,
    joiningDate: "2021-03-15",
    workMode: "Remote",
    status: "Active",
    avatarColor: "linear-gradient(135deg, #a855f7 0%, #d946ef 100%)",
    skills: ["React", "TypeScript", "Node.js", "System Design"]
  },
  {
    id: "ZAK-1002",
    fullName: "Ananya Patel",
    email: "ananya.patel@zakvid.in",
    phone: "+91 98123 45678",
    location: "Mumbai",
    department: "Design",
    designation: "Principal Product Designer",
    salary: 1620000,
    joiningDate: "2020-11-10",
    workMode: "Hybrid",
    status: "Active",
    avatarColor: "linear-gradient(135deg, #c084fc 0%, #ec4899 100%)",
    skills: ["Figma", "Design Systems", "UX Research", "Motion"]
  },
  {
    id: "ZAK-1003",
    fullName: "Rohan Verma",
    email: "rohan.verma@zakvid.in",
    phone: "+91 97654 32109",
    location: "Gurgaon",
    department: "Finance",
    designation: "Financial Controller",
    salary: 1500000,
    joiningDate: "2022-06-01",
    workMode: "On-site",
    status: "Active",
    avatarColor: "linear-gradient(135deg, #818cf8 0%, #c084fc 100%)",
    skills: ["Corporate Finance", "Taxation", "Financial Modeling"]
  },
  {
    id: "ZAK-1004",
    fullName: "Priyansh Gupta",
    email: "priyansh.gupta@zakvid.in",
    phone: "+91 99887 76655",
    location: "Hyderabad",
    department: "Engineering",
    designation: "Cloud DevOps Architect",
    salary: 1980000,
    joiningDate: "2023-01-09",
    workMode: "Remote",
    status: "Active",
    avatarColor: "linear-gradient(135deg, #9333ea 0%, #4f46e5 100%)",
    skills: ["AWS", "Kubernetes", "Docker", "Terraform"]
  },
  {
    id: "ZAK-1005",
    fullName: "Kavya Reddy",
    email: "kavya.reddy@zakvid.in",
    phone: "+91 96543 21098",
    location: "Hyderabad",
    department: "HR",
    designation: "Talent Acquisition Lead",
    salary: 1240000,
    joiningDate: "2021-07-05",
    workMode: "Hybrid",
    status: "Active",
    avatarColor: "linear-gradient(135deg, #e879f9 0%, #a855f7 100%)",
    skills: ["Tech Recruiting", "HR Operations", "People Analytics"]
  },
  {
    id: "ZAK-1006",
    fullName: "Vikramaditya Singh",
    email: "vikram.singh@zakvid.in",
    phone: "+91 95432 10987",
    location: "Delhi NCR",
    department: "Sales",
    designation: "Enterprise Growth Director",
    salary: 1750000,
    joiningDate: "2019-08-22",
    workMode: "On-site",
    status: "On Leave",
    avatarColor: "linear-gradient(135deg, #a855f7 0%, #818cf8 100%)",
    skills: ["Enterprise B2B", "Key Accounts", "Revenue Strategy"]
  },
  {
    id: "ZAK-1007",
    fullName: "Ishaan Malhotra",
    email: "ishaan.malhotra@zakvid.in",
    phone: "+91 94321 09876",
    location: "Pune",
    department: "Marketing",
    designation: "Head of Growth Marketing",
    salary: 1480000,
    joiningDate: "2022-09-18",
    workMode: "Hybrid",
    status: "Active",
    avatarColor: "linear-gradient(135deg, #d946ef 0%, #c084fc 100%)",
    skills: ["Growth Strategy", "Performance Ads", "Brand Scaling"]
  },
  {
    id: "ZAK-1008",
    fullName: "Meera Joshi",
    email: "meera.joshi@zakvid.in",
    phone: "+91 93210 98765",
    location: "Bengaluru",
    department: "Engineering",
    designation: "Fullstack Systems Developer",
    salary: 1400000,
    joiningDate: "2024-02-12",
    workMode: "Remote",
    status: "Inactive",
    avatarColor: "linear-gradient(135deg, #71717a 0%, #52525b 100%)",
    skills: ["Python", "PostgreSQL", "GraphQL", "FastAPI"]
  }
];
